package scims.model.fluentbuilders.competition;

public interface FluentWithIsSameNumberOfEventsForAllWeightClasses {
    FluentWithWeightClasses withIsSameNumberOfEventsForAllWeightClasses(boolean isSameNumberOfEventsForAllWeightClasses);
}
