name: Build with Java 11

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'  # Add the 'distribution' input with 'adopt' as the value
      - name: Check Gradle Version
        run: ./gradlew --version

      - name: Clean
        run: ./gradlew clean

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-app-artifact
          path: build/libs/SCIMS-1.0-SNAPSHOT.jar